### ISSUE TITLE
Could not work on sponge forge 1.12.2

### ISSUE THREAD

**Issue by Tollainmear** [Shynixn/PetBlocks#118]
### What happend:
the GUI was empty while execute `/petblock` from player, then the exceptions appeared at console.

### Exceptions appeared : 
[Gist](https://gist.github.com/Tollainmear/1fd1fc335bfe84177a7d63f23ca38163)

### info:
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-a312749
    SpongeForge: 1.12.2-2655-7.1.0-BETA-3041
    Minecraft Forge: 14.23.3.2655
    PetBlock: 7.0.0-SNAPSHOT

### BTW
 may I share this plugin to the [mcbbs](http://www.mcbbs.net/portal.php)? the biggest MC forum in China, I will only leave a link to your official download page

**Comment by Shynixn** [comment]
Thank you for this feedback. This was more like a testing snapshot to find out how the whole Sponge Ore release works and my maven hook into ForgeGradle merges with my build and release process. This will be fixed in the final v7.0.0 release. 

Sure, you are allowed to share this plugin, please link [this page]([url](https://github.com/Shynixn/PetBlocks/releases) and wait until the final v7.0.0 release. (Should be this weekend).

**Comment by Tollainmear** [comment]
nice! thank you for the reply~ 😘
