### ISSUE TITLE
Pets can't change worlds?

### ISSUE THREAD

**Issue by Cryptite** [Shynixn/PetBlocks#286]
This may be related to API usage, but I can't for the life of me figure out the proper way to get pets to change worlds. 

Left alone, they don't change worlds. Using this code to try to remove them:
`if (petService.hasPet(p)) {
            petService.getOrSpawnPetFromPlayer(p).ifPresent(PetProxy::remove);
        }`

followed by spawning them:
`Optional<PetProxy> b = petService.getOrSpawnPetFromPlayer(player);
        b.ifPresent(petProxy -> {
            currentPet.updatePet(player, petProxy);
            petProxy.teleport(player.getLocation());
        });`

They seem stuck in the old world position. If I relog, however, they will properly spawn in the new world, but that's as far as they seem to go. API docs were scarce last I looked after the big update, so I don't know if there're better ways to handle this but it does seem weird to have to get the pet or SPAWN it only to remove it, which seems to happen sometimes.

**Comment by Shynixn** [comment]
Pets should change the world together with their owners. If the pet stays in the original world then this is a bug and needs to be fixed. 

Regarding the API in general:

* If you want to know if a player has got a pet, you can use the ``$petService.hasPet(...) `` function. 
* If you want to perform operations on a pet, you can use the  ``$petService.getOrSpawnPetFromPlayer(..).  ``
* The function  ``$currentPet.updatePet(..) `` does not exist as far as I know?
* The ``$petService.getOrSpawnPetFromPlayer(..).  `` returns an optional as it cannot be guaranteed that the pet is currently available or even spawned correctly.

**Comment by Cryptite** [comment]
Ah, updatePet is my own method which, after spawning a pet, applies all the properties to it to create the kind of pet we want 
![image](https://user-images.githubusercontent.com/399721/64437053-261d5980-d08b-11e9-83ef-b1d0d61dc16b.png)

Otherwise, yeah, those are all the methods I ultimately use to turn pets on/off, etc. Far as I can tell though, aside from using the API in a test to spawn the pet, if I warp to another world it doesn't come with me.

**Comment by Shynixn** [comment]
I see. Allow me to mark this github issue as bug for world teleporting, thanks for reporting! 
Fixing this probably needs an NMS change and simply executing the teleporting function may cause troubles with pathfinding AIS. 

By the way, how do you feel working with the new API?

**Comment by Cryptite** [comment]
It's better than the last round for sure, though I think I would like a `getPetFromPlayer` that does not forcibly also create one. `hasPet` may tell me if the player has one, but if I wanted to get one that existed. Either that or `removePetFromPlayer` that could be called without potentially getting into a scenario where I wind up creating one to then delete it.

That just may be down to some bugs though.

**Comment by Shynixn** [comment]
The problem with ``getPetFromPlayer`` is that adding it would cause a ``spawnPet`` method which finally need to act differently depending on if the player has got a pet or does not have a pet yet. PetBlocks does only allow players to have one pet at a time per design which is not going to change. 

You could return the same pet instance instead of creating a new one or throw an exception if the pet already exists. The first option causes the same behaviour as ``getPetFromPlayer()`` which makes the whole interface confusing with 2 function behaving the exactly the same. The second option just returns the responsibility to the caller which I do not need in PetBlocks. 

This was also a design choice as it gurantees the user immediatly that only one pet can exist at once. 

I guess you mean that one check is required less? I agree with you in **this special case if you like to remove the pet.** However, PetBlocks has got more actions concerning **creating and editing** the pet, so there are more advantages left. From a designer perspective these methods will always behave the same regardless if other plugins interferred and cannot be misused. 

Below you can find some examples with the first option being the current implementation and the second one with a getPet method:

Add:

```Player player; //SomePlayer
petService.getOrSpawnPet(player).ifPresent { pet ->
   pet.teleport(...)
}
```

```Player player; //SomePlayer
if(service.hasPet(player) == false){
    petService.spawnPet(player)
}

petService.getPet(player).ifPresent{ pet ->
  pet.teleport(...)
}
```

Edit:

```Player player; //SomePlayer
petService.getOrSpawnPet(player).ifPresent { pet ->
   pet.teleport(...)
}
```

```Player player; //SomePlayer
if(service.hasPet(player) == false){
    petService.spawnPet(player)
}

petService.getPet(player).ifPresent{ pet ->
 pet.teleport(...)
}
```

Remove:

```Player player; //SomePlayer
if(service.hasPet(player)){
    petService.getOrSpawnPet(player).ifPresent{ pet ->
              pet.remove()
   } 
}
```
```
Player player; //SomePlayer
petService.getPet(player).ifPresent{ pet ->
         pet.remove()
}
```

You may want to argue that you do not want to spawn a pet when the user requests editing a pet? Well, from implementation details this is rarely being required.

**Comment by Cryptite** [comment]
Yeah, I'm certainly not advocating for multiple pets. Presumably if everything was working like it should, getOrSpawnPet wouldn't be a big deal when wanting to _remove_ a pet because it would always just _get_ and never spawn one (since you have one already). If the world-switch thing is actually an issue and gets fixed, then I may be raising an unnecessary fuss.

**Comment by Shynixn** [comment]
@Cryptite Set the warp delay value in the config to 6 or higher and the pet should follow you cross worlds.

**Comment by Cryptite** [comment]
Is it `teleport-delay`? I have it set to 20 so far and no luck.
