### ISSUE TITLE
Add Chinese translation

### ISSUE THREAD

**Issue by yudonglin** [Shynixn/PetBlocks#295]
There is no .lang file... So I just upload the config.yml?

**Comment by Shynixn** [comment]
Hi yoshino-lin!

Thank you for offering to provide a Chinese translation. However, I currently do not have any kind of lang files to support this case. If possible please submit a changed config.yml then I'll add it later on when lang files are supported.

**Comment by yoshino-lin** [comment]
understood

**Comment by yoshino-lin** [comment]
> Hi yoshino-lin!
> 
> Thank you for offering to provide a Chinese translation. However, I currently do not have any kind of lang files to support this case. If possible please submit a changed config.yml then I'll add it later on when lang files are supported.

Please check the pull requests. By the way, you can create a Folder called localization and put my transactions file inside.

**Comment by Shynixn** [comment]
I'll review your pull request later on and merge it to a feature branch.

**Comment by Shynixn** [comment]
Hi @yudonglin!

I have finally added your translation to PetBlocks. It too me a while because I wanted to refactor PetBlocks to support .lang files. 

As I have introduced new features in the meanwhile, the chinese translation lacks of some translations. I woud appreciate it if you could take a look at the new translation file. :) 

The new translation files can be found on the snapshot branch:

https://github.com/Shynixn/PetBlocks/tree/development/petblocks-core/src/main/resources/assets/petblocks/lang

**Comment by yudonglin** [comment]
Sure, please give me a few hours.

Christoph <notifications@github.com>于2020年2月27日 周四上午6:09写道：

**Comment by yudonglin** [comment]
> Hi @yudonglin!
> 
> I have finally added your translation to PetBlocks. It too me a while because I wanted to refactor PetBlocks to support .lang files.
> 
> As I have introduced new features in the meanwhile, the chinese translation lacks of some translations. I woud appreciate it if you could take a look at the new translation file. :)
> 
> The new translation files can be found on the snapshot branch:
> 
> https://github.com/Shynixn/PetBlocks/tree/development/petblocks-core/src/main/resources/assets/petblocks/lang

Done, please check the pull requests.
