### ISSUE TITLE
Pay for pet

### ISSUE THREAD

**Issue by Bloodlex** [Shynixn/PetBlocks#508]
Hey,

Could you please add support for Vault economy, so I can pay to get a pet? 😁

Thank you very much!

**Comment by Shynixn** [comment]
Hi,

PetBlocks does not offer a shop system in the GUI because this is not a focus of the plugin. However, you can hide or block certain actions in the PetBlocks GUI if a user does not have sufficient permissions. The permissions can be defined by yourself and sold via any external permission shop plugin.
