### ISSUE TITLE
Disconnect on Join after enabling my petblock

### ISSUE THREAD

**Issue by MWFIAE** [Shynixn/PetBlocks#54]
[11:50:05 INFO]: MWFIAE[/47.68.100.102:59128] logged in with entity id 292 at ([mw_testwelt]14.27701800520191, 130.0, 0.8900479674627422)
[11:50:07 INFO]: MWFIAE lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown mob network type id -1

Using Spigot 1.12.2, latest petblocks, latest version of protocollib and protocolsupport. 
It doesn't seem to occur if tested without protocolsupport.

**Comment by Shynixn** [comment]
Thanks for reporting! Same reason as [issue53](https://github.com/Shynixn/PetBlocks/issues/53) as it is related to the custom entity registry. 

I'm going to test it with protocolsupport.

**Comment by MWFIAE** [comment]
Thanks a lot!
Hope this is resolved soon :)

**Comment by Shynixn** [comment]
I cannot recreate this issue, even when I have installed protocollib and protocolsupport. Still, I'm quite sure your problem is resolved now as I patched the way when entities get registered.

Please download the [latest snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/petblocks/petblocks-bukkit-plugin/6.3.1-SNAPSHOT/petblocks-bukkit-plugin-6.3.1-20171107.173330-3-jar-with-dependencies.jar) and check if your problem is resolved. As the config did not change you only need to override the PetBlocks.jar in your plugin folder.

**Comment by MWFIAE** [comment]
Didn't help :(
[18:53:09 INFO]: [PetBlocks] Enabled PetBlocks 6.3.1-SNAPSHOT by Shynixn
[18:53:10 INFO]: [PetBlocks] ================================================
[18:53:10 INFO]: [PetBlocks] You are using a snapshot of PetBlocks
[18:53:10 INFO]: [PetBlocks] Please check regularly if there is a new version
[18:53:10 INFO]: [PetBlocks] ================================================
[18:53:28 INFO]: MWFIAE issued server command: /petblock
[18:53:34 INFO]: MWFIAE lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown mob network type id -1

And my testing shows that it isn't ProtocolSupport alone, but only occurs if one uses the protocolsupport addons: ProtocolSupportStuff and ProtocolSupportLegacySupport.

**Comment by Shynixn** [comment]
Hm, I don't really think that ProtocolSupport causes these problems. This message appears when the entity is not properly registered and plugins like ProtocolSupport or ViaVersion gets used. 

Can you think of any other pet/mob/npc plugins you have installed? 
Did you also try using just PetBlocks and ProtocolSupport? Adding your plugins one by one could help locating it.

**Comment by MWFIAE** [comment]
Well with all plugins it doesn't work. With all plugins except ProtocolSupportStuff and ProtocolSupportLegacySupport it works. 

I will try tomorrow, but I need to setup a proper test environment first :)

As for mob/npc-related plugins, we are using mythicmobs and citizens2.

**Comment by Shynixn** [comment]
Well it would help a lot if you can detect the reason as I could fix compatibilty issues with that plugin. 

The reason why I believe another NPC plugin is responsible for this problem is this [issue](https://github.com/ProtocolSupport/ProtocolSupport/issues/687) on the ProtocolSupport github page.

Also I hope you do not try to join the server with a client version below 1.8.0 as PetBlocks cannot support this.

**Comment by MWFIAE** [comment]
I tried to reproduce it on a lokalserver (to speed up testing) but I couldn't trigger the bug. 
So it could be a few different things, maybe it has something to do with os, bungeecord, or basically any plugin using mysql (as I haven't set up a database locally).
I will try to do further testing once I find the time to do so.

**Comment by Shynixn** [comment]
Sure, if you are willing to do all of this work just for PetBlocks. ;) Sorry that I cannot help you any further but as you said it's very difficult to reproduce the issue :/

I'll probably release the changes this weekend but except from cleaning up there won't be any differences compared to the latest snapshot.

**Comment by MWFIAE** [comment]
What should I say... Players love there little buddys *shrug* ;3

**Comment by Shynixn** [comment]
Did you get any results?
@MWFIAE

**Comment by MWFIAE** [comment]
Ah sry, I didn't have the time lately to further test this issue. 
I will close it until I get further data, thx for your time. 
Happy Holidays :)
